db:
 driver             : redshift
 dbname             : mycdm
 dbuser             : 
 dbpass             : 
 dbhost             : ohdsitutorialtest2-ohdsielas-redshiftclustermulti-1sizz9gq0e4uq.cc8ltappgfjt.us-east-1.redshift.amazonaws.com/mycdm
 dbport             : 5439
 schema             : mimiciii100
 vocab_schema       : mimiciii100
 dqa_schema         : mimiciii100
 argos_config_file_path : ../argos/argos_config.json
reporting:
 site_directory     : ../Results
 etl_script_version : v1
 dqa_script_version : v3.0.0
 site               : Sample
 cdm                : PEDSnet
 conventions_version : 3.0.0 
